.\bin\ycsb.bat run rest -s -P workloads/workload_b | Out-File .\result_workload_b.txt;
.\bin\ycsb.bat run rest -s -P workloads/workload_a | Out-File .\result_workload_a.txt;
.\bin\ycsb.bat run rest -s -P workloads/workload_c | Out-File .\result_workload_c.txt;
.\bin\ycsb.bat run rest -s -P workloads/workload_d | Out-File .\result_workload_d.txt;
.\bin\ycsb.bat run rest -s -P workloads/workload_e | Out-File .\result_workload_e.txt;